name: Lint Validation
on:
  push:
    branches:
      - '*'         # matches every branch
      - '*/*'       # matches every branch containing a single '/'
      - '!master'   # excludes master
jobs:
  lint:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: '0'
    - uses: actions/setup-node@v1
      with:
        node-version: '12.18.3'
    - name: install dependencies
      run: yarn install
    - name: Lint file
      run: yarn run lint